name: Azure Template Validation 
on: 
    workflow_dispatch:
    push:
        branches:
            - main
permissions: 
  contents: read 
  id-token: write 
  pull-requests: write 
jobs: 
  template_validation_job: 
    runs-on: ubuntu-latest 
    environment: production
    name: Template validation 
    steps: 
      # Step 1: Checkout the code from your repository 
      - name: Checkout code 
        uses: actions/checkout@v4 
      # Step 2: Validate the Azure template using microsoft/template-validation-action 
      - name: Validate Azure Template 
        uses: microsoft/template-validation-action@Latest
        id: validation 
        with: 
            useDevContainer: false
        env: 
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }} 
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      # Step 3: Print the result of the validation 
      - name: Print result 
        run: cat ${{ steps.validation.outputs.resultFile }} 
