name: Build ResearchAssistant Docker Images

on:
  push:
    branches: [main, dev, demo]
    paths:
      - ResearchAssistant/**
  pull_request:
    branches: [main, dev, demo]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - ResearchAssistant/**
  merge_group:
  workflow_dispatch:

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - app_name: byoaia-app
            dockerfile: ResearchAssistant/App/WebApp.Dockerfile
            password_secret: DOCKER_PASSWORD_RESEARCHASSISTANT

    uses: ./.github/workflows/build-docker.yml
    with:
      registry: byoaiacontainerreg.azurecr.io
      username: byoaiacontainerreg
      password_secret: ${{ matrix.password_secret }}
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: ${{ github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo' || github.ref_name == 'dependabotchanges' }} 
    secrets: inherit
